[package]
name = "easy-analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
petgraph = "0.8.2"
regex = "1.11.1"
tracing = "0.1.41"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
thiserror = "2.0.12"
semver = "1.0.26"

[package.metadata.rust-analyzer]
rustc_private = true